/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c1c6d7",
        "outline": "#8b90a0",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "primary": "#adc6ff",
        "inverse-on-surface": "#313030",
        "on-secondary": "#3a0093",
        "on-surface": "#e5e2e1",
        "primary-fixed-dim": "#adc6ff",
        "background": "#131313",
        "error": "#ffb4ab",
        "surface-tint": "#adc6ff",
        "on-primary-fixed": "#001a41",
        "tertiary-container": "#ff5625",
        "error-container": "#93000a",
        "on-secondary-container": "#d2c0ff",
        "on-secondary-fixed-variant": "#5300cd",
        "secondary-fixed": "#e8ddff",
        "on-tertiary-fixed-variant": "#872000",
        "tertiary-fixed-dim": "#ffb5a0",
        "outline-variant": "#414755",
        "on-primary": "#002e69",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#cfbdff",
        "surface-container": "#201f1f",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed": "#ffdbd1",
        "on-tertiary": "#601400",
        "on-secondary-fixed": "#22005d",
        "surface-variant": "#353534",
        "on-tertiary-container": "#541100",
        "on-primary-container": "#00285c",
        "surface": "#131313",
        "on-error": "#690005",
        "surface-bright": "#393939",
        "inverse-surface": "#e5e2e1",
        "secondary-container": "#6305ef",
        "secondary": "#cfbdff",
        "primary-container": "#4b8eff",
        "on-tertiary-fixed": "#3b0900",
        "surface-container-highest": "#353534",
        "primary-fixed": "#d8e2ff",
        "tertiary": "#ffb5a0",
        "on-primary-fixed-variant": "#004493",
        "inverse-primary": "#005bc1"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"
      },
    },
  },
  plugins: [],
}
